steps:
#step 1
- name: 'gcr.io/cloud-builders/docker'
  entrypoint: 'bash'
  args: [
   '-c',
   'docker pull gcr.io/project-kubernetes-242705/guestbook:latest || exit 0'
  ]
#step 2
- name: 'gcr.io/cloud-builders/docker'
  args: [
   'build',
   '-t',
   'gcr.io/project-kubernetes-242705/guestbook:$BRANCH_NAME-$COMMIT_SHA',
   '.'
  ]
#step 3
- name: 'gcr.io/cloud-builders/kubectl'
  args: ['apply', '-f', 'kb8/']
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=asia-south1-a'
  - 'CLOUDSDK_CONTAINER_CLUSTER=guestbook'
#step 4
- name: 'gcr.io/cloud-builders/kubectl'
  args: [
   'set',
   'image',
   'deployment',
   'guestbook',
   'guestbook=gcr.io/project-kubernetes-242705/guestbook:$BRANCH_NAME-$COMMIT_SHA'
  ]
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=asia-south1-a'
  - 'CLOUDSDK_CONTAINER_CLUSTER=guestbook'
# push images to Google Container Registry with tags
images: [
   'gcr.io/project-kubernetes-242705/guestbook:$BRANCH_NAME-$COMMIT_SHA',
  ]
